import type { CompetitorProfile, MarketSignal, MichaelTask } from "./types";

export const COMPETITOR_SOURCE_PATH = "10_Sources/Source - Competitor Websites - 2026-07-15.md";
export const MARKET_SOURCE_PATH = "06_Research/Market Evidence and Source Map.md";
export const MICHAEL_ROLE_SOURCE_PATH = "03_GTM/Michael Role Charter.md";
export const AI_SOURCE_PATH = "06_Research/AI Opportunity Register.md";

export const competitorProfiles = [
  {
    id: "bluecargo",
    name: "BlueCargo",
    url: "https://www.bluecargo.io/post/are-you-ready-to-navigate-the-final-fmc-ruling",
    category: "audit",
    categoryLabel: "Audit and prevention",
    specialization: 4,
    workflowBreadth: 4.2,
    offer: "Invoice checks, event and contract validation, disputes, and historical audit.",
    pricingSignal: "Free tier; Pro displayed from $18,126 per year.",
    evidenceBoundary: "Outcomes are vendor claims and some regulatory copy is stale.",
  },
  {
    id: "unwaived",
    name: "Unwaived",
    url: "https://www.unwaived.com/",
    category: "recovery",
    categoryLabel: "Recovery specialist",
    specialization: 5,
    workflowBreadth: 2.3,
    offer: "Evidence packets, filing, follow-up, and credit tracking.",
    pricingSignal: "Conflicting public success-fee wording from 20% to 35%.",
    evidenceBoundary: "Its public pilot snapshot showed zero invoices and zero recovery.",
  },
  {
    id: "harborclaim",
    name: "HarborClaim",
    url: "https://harborclaim.com/",
    category: "recovery",
    categoryLabel: "Recovery specialist",
    specialization: 4.8,
    workflowBreadth: 1.9,
    offer: "Invoice review, dispute packets, follow-up, and recovery tracking.",
    pricingSignal: "Free review; typical 30% of recovered value.",
    evidenceBoundary: "No named public outcomes were observed.",
  },
  {
    id: "auditdray",
    name: "AuditDray",
    url: "https://auditdray.com/",
    category: "recovery",
    categoryLabel: "Recovery specialist",
    specialization: 5.2,
    workflowBreadth: 2,
    offer: "AI-positioned invoice audit and dispute generation.",
    pricingSignal: "First three months free; later savings share undisclosed.",
    evidenceBoundary: "Published recovery figures are unsupported vendor claims.",
  },
  {
    id: "miraledger",
    name: "MiraLedger",
    url: "https://www.miraledger.io/",
    category: "recovery",
    categoryLabel: "Recovery specialist",
    specialization: 4.9,
    workflowBreadth: 2.6,
    offer: "Carrier invoice audit, dispute packs, and recovery reporting.",
    pricingSignal: "Pilot and volume plans; quote required.",
    evidenceBoundary: "Pilots, maturity, and outcomes remain unverified.",
  },
  {
    id: "intelligent-audit",
    name: "Intelligent Audit",
    url: "https://www.intelligentaudit.com/case-studies/reducing-demurrage-and-detention-costs-through-invoice-validation",
    category: "audit",
    categoryLabel: "Audit and prevention",
    specialization: 2.5,
    workflowBreadth: 4.6,
    offer: "Broad multimodal freight audit with a D&D case study.",
    pricingSignal: "Enterprise pricing is not public.",
    evidenceBoundary: "The case is anonymized and audit-point counts vary.",
  },
  {
    id: "gocomet",
    name: "GoComet",
    url: "https://www.gocomet.com/solutions/reduce-supply-chain-costs",
    category: "audit",
    categoryLabel: "Audit and prevention",
    specialization: 2.1,
    workflowBreadth: 4.2,
    offer: "Visibility, tracking, procurement, and D&D prevention.",
    pricingSignal: "Basic tracker free; advanced plans by quote.",
    evidenceBoundary: "Prevention claims do not validate recovery performance.",
  },
  {
    id: "dockline",
    name: "Dockline",
    url: "https://docklineai.com/",
    category: "audit",
    categoryLabel: "Audit and prevention",
    specialization: 3.8,
    workflowBreadth: 4.6,
    offer: "Drayage invoice audit, contract checks, terminal data, and evidence packs.",
    pricingSignal: "No public price observed.",
    evidenceBoundary: "Product maturity, customers, and outcomes remain unverified.",
  },
  {
    id: "portside-recovery",
    name: "Portside Recovery",
    url: "https://portsiderecovery.com/",
    category: "recovery",
    categoryLabel: "Recovery specialist",
    specialization: 4.6,
    workflowBreadth: 1.7,
    offer: "Specialist D&D dispute recovery in Australia.",
    pricingSignal: "30% success fee with a displayed per-dispute cap.",
    evidenceBoundary: "Adjacent geography and different legal context.",
  },
  {
    id: "nvision",
    name: "nVision Global",
    url: "https://corporate.nvisionglobal.com/",
    category: "enterprise",
    categoryLabel: "Enterprise audit",
    specialization: 1,
    workflowBreadth: 5,
    offer: "Freight audit, payment, governance, and financial intelligence.",
    pricingSignal: "Enterprise quote.",
    evidenceBoundary: "Published figures are company claims, including sponsored content.",
  },
  {
    id: "trax",
    name: "Trax",
    url: "https://www.traxtech.com/products/freight-audit",
    category: "enterprise",
    categoryLabel: "Enterprise audit",
    specialization: 1.2,
    workflowBreadth: 4.7,
    offer: "Global freight audit, payment, data, and analytics.",
    pricingSignal: "Enterprise quote.",
    evidenceBoundary: "Scale and savings claims require independent comparison.",
  },
  {
    id: "cass",
    name: "Cass",
    url: "https://www.cassinfo.com/freight-audit-payment",
    category: "enterprise",
    categoryLabel: "Enterprise audit",
    specialization: 1.4,
    workflowBreadth: 5.3,
    offer: "Freight audit, payment, business intelligence, and integration.",
    pricingSignal: "Enterprise quote.",
    evidenceBoundary: "Customer and savings claims are vendor-controlled.",
  },
  {
    id: "ct-logistics",
    name: "CT Logistics",
    url: "https://www.ctlogistics.com/auditpay",
    category: "enterprise",
    categoryLabel: "Enterprise audit",
    specialization: 1.6,
    workflowBreadth: 4.5,
    offer: "Freight bill audit, payment, reporting, and transportation management.",
    pricingSignal: "Enterprise quote.",
    evidenceBoundary: "D&D is one workflow inside a broader offer.",
  },
  {
    id: "data2logistics",
    name: "Data2Logistics / Loop",
    url: "https://www.data2logistics.com/",
    category: "enterprise",
    categoryLabel: "Enterprise audit",
    specialization: 1.8,
    workflowBreadth: 4.9,
    offer: "Freight audit, payment, data normalization, and spend visibility.",
    pricingSignal: "Enterprise quote.",
    evidenceBoundary: "Comparative outcomes and traction were not independently verified.",
  },
] satisfies readonly CompetitorProfile[];

export const marketSignals = [
  {
    id: "charges",
    value: "$15.4B",
    label: "D&D charges collected",
    meaning: "Nine major carriers reported this charge pool across the stated five-year window.",
    boundary: "Not the invalid, disputable, recoverable, or obtainable amount.",
    url: "https://www.fmc.gov/detention-and-demurrage/",
  },
  {
    id: "complaints",
    value: "296",
    label: "FY2025 complaints received",
    meaning: "The FMC reports 164 accepted complaints and about $2.89M in FY2025 relief.",
    boundary: "One public route, not all direct disputes or a recovery-rate denominator.",
    url: "https://www.fmc.gov/wp-content/uploads/2026/04/FY-2025-Annual-Report.pdf",
  },
  {
    id: "importers",
    value: "239,231",
    label: "Identified U.S. importers",
    meaning: "The preliminary 2024 Census profile gives a broad account universe.",
    boundary: "All modes; not an ocean, D&D exposure, or buyer count.",
    url: "https://www.census.gov/foreign-trade/Press-Release/edb/2024prelimprofile.pdf",
  },
  {
    id: "providers",
    value: "14",
    label: "Observed providers",
    meaning: "Direct, adjacent, and enterprise alternatives make the category congested.",
    boundary: "Provider count is not market demand or traction.",
  },
] satisfies readonly MarketSignal[];

export const marketFriction = [
  {
    step: "Disruption",
    issue: "Closures, holds, congestion, and route shocks create delay and complexity.",
    proof: "Port and multilateral reports measure recurrent operational pressure.",
  },
  {
    step: "Invoice",
    issue: "The bill arrives with short deadlines, multiple parties, and uneven backup.",
    proof: "Official complaint guidance requires invoices, facts, and supporting documents.",
  },
  {
    step: "Evidence",
    issue: "Terms, dates, availability, appointments, actions, and causation must align.",
    proof: "Official cases show that liability and operational facts are case-specific.",
  },
  {
    step: "Decision",
    issue: "Teams must choose to pay, dispute, escalate, or stop a weak case.",
    proof: "Public practitioner posts repeatedly expose missing backup and unclear ownership.",
  },
] as const;

export const marketEvidenceGroups = [
  {
    label: "Official and multilateral",
    boundary: "Market and disruption context, not invoice eligibility.",
    links: [
      { label: "World Bank CPPI 2025", url: "https://www.worldbank.org/en/topic/transport/publication/cppi" },
      { label: "UNCTAD Maritime Transport 2025", url: "https://unctad.org/publication/review-maritime-transport-2025" },
      { label: "New York Fed GSCPI", url: "https://www.newyorkfed.org/research/policy/gscpi" },
      { label: "IMF PortWatch", url: "https://www.imf.org/en/news/articles/2023/11/13/pr23390-imf-university-oxford-launch-portwatch-platform-monitor-simulate-trade-disruptions" },
    ],
  },
  {
    label: "Research papers",
    boundary: "Mechanisms and measurement, not U.S. market size or SheperD outcomes.",
    links: [
      { label: "D&D regimes and inland transport", url: "https://doi.org/10.1016/j.trc.2018.01.012" },
      { label: "Long container dwell time", url: "https://ojs.lib.unideb.hu/IJEMS/article/view/9774" },
      { label: "GSCPI research paper", url: "https://www.newyorkfed.org/research/staff_reports/sr1017" },
    ],
  },
  {
    label: "Public problem language",
    boundary: "Interview and content inputs only, never prevalence or legal evidence.",
    links: [
      { label: "30+ day exam hold", url: "https://www.reddit.com/r/logistics/comments/1nkbihf/" },
      { label: "Missing forwarder backup", url: "https://www.reddit.com/r/logistics/comments/1r6iyd1/customs_exam_charges_from_freight_forwarder/" },
      { label: "Inspection charge questions", url: "https://www.reddit.com/r/logistics/comments/1r26mfj/outrageous_inspection_charges/" },
      { label: "Freight invoice audit workflow", url: "https://www.reddit.com/r/logistics/comments/vwkbtd/do_you_audit_your_invoices/" },
    ],
  },
] as const;

export const marketTiming = [
  {
    label: "Why now",
    title: "The evidence burden is visible",
    detail: "Invoice-field rules, formal complaint routes, enforcement, and public pressure make traceability a real buyer concern.",
  },
  {
    label: "Why not scale yet",
    title: "The commercial bridge is missing",
    detail: "No admitted cohort proves eligible share, realized recovery, workload, willingness to pay, or unit economics.",
  },
  {
    label: "Best next proof",
    title: "One permissioned comparable cohort",
    detail: "Measure qualification, submission, case quality, work time, review time, cycle, and realized cash or credit.",
  },
] as const;

export const michaelTasks = [
  {
    id: "TASK-01",
    workstream: "Domain knowledge",
    outcome: "A cited question bank and explicit route boundary.",
    aiAssist: "Summarize admitted sources, retrieve exact passages, and draft questions.",
    humanDecision: "A qualified reviewer owns legal meaning, eligibility, and route selection.",
    state: "prepare-now",
    sourcePath: "06_Research/Industry Regulatory and Competitive Dossier.md",
  },
  {
    id: "TASK-02",
    workstream: "Value and journey",
    outcome: "One testable wedge from invoice intake to evidence-backed decision.",
    aiAssist: "Cluster pain language and map evidence gaps across the customer journey.",
    humanDecision: "Avi approves positioning, promise, and commercial scope.",
    state: "prepare-now",
    sourcePath: MICHAEL_ROLE_SOURCE_PATH,
  },
  {
    id: "TASK-03",
    workstream: "Technology and CRM",
    outcome: "A synthetic CRM with owners, gates, source links, and event definitions.",
    aiAssist: "Normalize records, flag missing fields, and draft weekly summaries.",
    humanDecision: "System access and real customer data need security and privacy approval.",
    state: "prepare-now",
    sourcePath: "04_Operations/CRM Data Model.md",
  },
  {
    id: "TASK-04",
    workstream: "Sales assets",
    outcome: "A claim-controlled deck, discovery guide, and evidence checklist.",
    aiAssist: "Draft variants from approved claims and flag unsupported wording.",
    humanDecision: "Avi approves commercial claims and any external use.",
    state: "prepare-now",
    sourcePath: "01_Company/Claims and Evidence Register.md",
  },
  {
    id: "TASK-05",
    workstream: "Digital and content",
    outcome: "A source-led content backlog tied to real buyer questions.",
    aiAssist: "Turn cited questions into outlines, comparison drafts, and update alerts.",
    humanDecision: "Publication requires domain, claim, and brand approval.",
    state: "prepare-now",
    sourcePath: "10_Sources/Source - GTM Market and Demand Scan - 2026-07-15.md",
  },
  {
    id: "TASK-06",
    workstream: "Customer and partner segments",
    outcome: "Named hypotheses for buyers, partners, triggers, and exclusions.",
    aiAssist: "Enrich public company context and cluster accounts by declared criteria.",
    humanDecision: "Targeting, contact authority, and outreach permission stay human-owned.",
    state: "prepare-now",
    sourcePath: "03_GTM/ICP and Stakeholder Personas.md",
  },
  {
    id: "TASK-07",
    workstream: "Governance",
    outcome: "A weekly decision cadence with owners, evidence, and stop rules.",
    aiAssist: "Prepare decision briefs, surface overdue gates, and reconcile metrics.",
    humanDecision: "Avi makes founder, pricing, claim, security, and activation decisions.",
    state: "prepare-now",
    sourcePath: "04_Operations/Operating Cadence and KPI Dictionary.md",
  },
  {
    id: "TASK-08",
    workstream: "Live sales",
    outcome: "One bounded, permissioned cohort after every required gate passes.",
    aiAssist: "Prepare research, drafts, follow-up options, and measurement capture.",
    humanDecision: "External contact, sending, representation, and final decisions require approval.",
    state: "approval-gated",
    sourcePath: "10_Sources/Source - 16 Week Engagement Plan.md",
  },
] satisfies readonly MichaelTask[];
